### ISSUE TITLE
Next/Prev buttons hide the calendar in Safari and Firefox

### ISSUE THREAD

**Issue by greypants** [vigetlabs/ca11y#36]
Safari 9.0.3, Firefox 44.0.2, probably others. 

:disappointed:

**Comment by greypants** [comment]
@averyvery is the resolved and published?

**Comment by averyvery** [comment]
Yes, sorry. Will close.

On Friday, March 11, 2016, Dan Tello notifications@github.com wrote:

> @averyvery https://github.com/averyvery is the resolved and published?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vigetlabs/ca11y/issues/36#issuecomment-195396054.

## 

_Doug Avery_
Front-End Development Director

703.891.0670 x138
720.666.3852 m
viget.com
http://www.google.com/url?q=http%3A%2F%2Fviget.com&sa=D&sntz=1&usg=AFrqEzcM3JYXwowZdGV1yX2CD2NWL_AHOA

This email may include confidential information. Please do not share unless
we agree otherwise.
